services:
  - type: web
    name: nana-ai
    env: python
    region: frankfurt
    buildCommand: python build.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1 --timeout-keep-alive 75 --no-access-log --no-server-header
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/src/data/model
      - key: TOKENIZERS_PARALLELISM
        value: "false"
    healthCheckPath: /ping
    autoDeploy: true
    disk:
      name: nana-storage
      mountPath: /opt/render/project/src/data
      sizeGB: 2
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
