services:
  - type: web
    name: nana-ai
    env: python
    region: frankfurt
    buildCommand: python build.py
    startCommand: python -c "import os; port = int(os.environ.get('PORT', 10000)); from app import app; import uvicorn; uvicorn.run(app, host='0.0.0.0', port=port, workers=1)"
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/src/data/model
      - key: TOKENIZERS_PARALLELISM
        value: "false"
    healthCheckPath: /ping
    autoDeploy: false
    disk:
      name: nana-storage
      mountPath: /opt/render/project/src/data
      sizeGB: 2
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
