services:
  - type: web
    name: nana-ai-assistant
    env: python
    region: frankfurt
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/data
      python -c '
      from transformers import BlenderbotTokenizer, BlenderbotForConditionalGeneration
      model_name = "facebook/blenderbot-400M-distill"
      cache_dir = "/opt/render/project/src/data/model"
      tokenizer = BlenderbotTokenizer.from_pretrained(model_name)
      model = BlenderbotForConditionalGeneration.from_pretrained(model_name)
      tokenizer.save_pretrained(cache_dir)
      model.save_pretrained(cache_dir)
      print(" Model cached successfully!")
      '
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/src/data/model
    healthCheckPath: /webhook
    autoDeploy: true
    disk:
      name: nana-storage
      mountPath: /opt/render/project/src/data
      sizeGB: 2
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
